title: Unity Secondary School
url: https://unitysec.moe.edu.sg
favicon: /images/unity-secondary-school.jpg
colors:
  primary-color: "#dec121"
  secondary-color: "#dec121"
  media-colors:
    - title: media-color-one
      color: "#dec121"
    - title: media-color-two
      color: "#dec121"
    - title: media-color-three
      color: "#dec121"
    - title: media-color-four
      color: "#dec121"
    - title: media-color-five
      color: "#dec121"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2i4e1lepc5foc.amplifyapp.com
prod: https://master.d2i4e1lepc5foc.amplifyapp.com
shareicon: /images/unity-secondary-school.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
